services:
  vendor-portal:
    image: pgavriluk/selenium
    environment:
      - BROWSER=chrome
      - HUB_HOST=hub
      - THREAD_COUNT=1
      - TEST_SUITE=vendor-portal.xml
    volumes:
      - ./output/vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
    image: pgavriluk/selenium
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - THREAD_COUNT=1
      - TEST_SUITE=flight-reservation.xml
    volumes:
      - ./output/flight-reservation:/home/selenium-docker/test-output